package com.gasguz.model.mybatis.dao;

import com.gasguz.model.mybatis.GasPrice;
import com.gasguz.model.mybatis.GasPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GasPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int countByExample(GasPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int deleteByExample(GasPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int insert(GasPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int insertSelective(GasPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    List<GasPrice> selectByExample(GasPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    GasPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GasPrice record, @Param("example") GasPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GasPrice record, @Param("example") GasPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GasPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_GAS_PRICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GasPrice record);
}