package com.gasguz.model.mybatis.dao;

import com.gasguz.model.mybatis.Transaction;
import com.gasguz.model.mybatis.TransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int countByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int deleteByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int insert(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int insertSelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    List<Transaction> selectByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    Transaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Transaction record, @Param("example") TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Transaction record, @Param("example") TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_TRANSACTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Transaction record);
}