package com.gasguz.model.mybatis.dao;

import com.gasguz.model.mybatis.UserGasAmount;
import com.gasguz.model.mybatis.UserGasAmountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGasAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int countByExample(UserGasAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int deleteByExample(UserGasAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int insert(UserGasAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int insertSelective(UserGasAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    List<UserGasAmount> selectByExample(UserGasAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    UserGasAmount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserGasAmount record, @Param("example") UserGasAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserGasAmount record, @Param("example") UserGasAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserGasAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_USER_GAS_AMOUNT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserGasAmount record);
}