package com.gasguz.model.mybatis.dao;

import com.gasguz.model.mybatis.Vendor;
import com.gasguz.model.mybatis.VendorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VendorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int countByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int deleteByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int insert(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int insertSelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    List<Vendor> selectByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    Vendor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GG_VENDOR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Vendor record);
}