package com.gasguz.model.mybatis;

import com.gasguz.action.AbstractForm;
import java.util.Date;

public class AuthorizedUser extends AbstractForm {
  private static final long serialVersionUID = 1L;

  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_AUTHORIZED_USER.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_AUTHORIZED_USER.FNAME
     *
     * @mbggenerated
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_AUTHORIZED_USER.LNAME
     *
     * @mbggenerated
     */
    private String lname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_AUTHORIZED_USER.PIN
     *
     * @mbggenerated
     */
    private String pin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_AUTHORIZED_USER.DATE_CREATED
     *
     * @mbggenerated
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_AUTHORIZED_USER.DATE_MODIFIED
     *
     * @mbggenerated
     */
    private Date dateModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_AUTHORIZED_USER.USER_ID
     *
     * @return the value of GG_AUTHORIZED_USER.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_AUTHORIZED_USER.USER_ID
     *
     * @param userId the value for GG_AUTHORIZED_USER.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_AUTHORIZED_USER.FNAME
     *
     * @return the value of GG_AUTHORIZED_USER.FNAME
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_AUTHORIZED_USER.FNAME
     *
     * @param fname the value for GG_AUTHORIZED_USER.FNAME
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_AUTHORIZED_USER.LNAME
     *
     * @return the value of GG_AUTHORIZED_USER.LNAME
     *
     * @mbggenerated
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_AUTHORIZED_USER.LNAME
     *
     * @param lname the value for GG_AUTHORIZED_USER.LNAME
     *
     * @mbggenerated
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_AUTHORIZED_USER.PIN
     *
     * @return the value of GG_AUTHORIZED_USER.PIN
     *
     * @mbggenerated
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_AUTHORIZED_USER.PIN
     *
     * @param pin the value for GG_AUTHORIZED_USER.PIN
     *
     * @mbggenerated
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_AUTHORIZED_USER.DATE_CREATED
     *
     * @return the value of GG_AUTHORIZED_USER.DATE_CREATED
     *
     * @mbggenerated
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_AUTHORIZED_USER.DATE_CREATED
     *
     * @param dateCreated the value for GG_AUTHORIZED_USER.DATE_CREATED
     *
     * @mbggenerated
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_AUTHORIZED_USER.DATE_MODIFIED
     *
     * @return the value of GG_AUTHORIZED_USER.DATE_MODIFIED
     *
     * @mbggenerated
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_AUTHORIZED_USER.DATE_MODIFIED
     *
     * @param dateModified the value for GG_AUTHORIZED_USER.DATE_MODIFIED
     *
     * @mbggenerated
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
}