package com.gasguz.model.mybatis;

import com.gasguz.action.AbstractForm;
import java.math.BigDecimal;
import java.util.Date;

public class GasPrice extends AbstractForm {
  private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_GAS_PRICE.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_GAS_PRICE.VENDOR_LOCATION_ID
     *
     * @mbggenerated
     */
    private Long vendorLocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_GAS_PRICE.GAS_GRADE_ID
     *
     * @mbggenerated
     */
    private Long gasGradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_GAS_PRICE.PRICE
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_GAS_PRICE.LAST_ID
     *
     * @mbggenerated
     */
    private Long lastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_GAS_PRICE.DATE_CREATED
     *
     * @mbggenerated
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_GAS_PRICE.DATE_MODIFIED
     *
     * @mbggenerated
     */
    private Date dateModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_GAS_PRICE.ID
     *
     * @return the value of GG_GAS_PRICE.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_GAS_PRICE.ID
     *
     * @param id the value for GG_GAS_PRICE.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_GAS_PRICE.VENDOR_LOCATION_ID
     *
     * @return the value of GG_GAS_PRICE.VENDOR_LOCATION_ID
     *
     * @mbggenerated
     */
    public Long getVendorLocationId() {
        return vendorLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_GAS_PRICE.VENDOR_LOCATION_ID
     *
     * @param vendorLocationId the value for GG_GAS_PRICE.VENDOR_LOCATION_ID
     *
     * @mbggenerated
     */
    public void setVendorLocationId(Long vendorLocationId) {
        this.vendorLocationId = vendorLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_GAS_PRICE.GAS_GRADE_ID
     *
     * @return the value of GG_GAS_PRICE.GAS_GRADE_ID
     *
     * @mbggenerated
     */
    public Long getGasGradeId() {
        return gasGradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_GAS_PRICE.GAS_GRADE_ID
     *
     * @param gasGradeId the value for GG_GAS_PRICE.GAS_GRADE_ID
     *
     * @mbggenerated
     */
    public void setGasGradeId(Long gasGradeId) {
        this.gasGradeId = gasGradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_GAS_PRICE.PRICE
     *
     * @return the value of GG_GAS_PRICE.PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_GAS_PRICE.PRICE
     *
     * @param price the value for GG_GAS_PRICE.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_GAS_PRICE.LAST_ID
     *
     * @return the value of GG_GAS_PRICE.LAST_ID
     *
     * @mbggenerated
     */
    public Long getLastId() {
        return lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_GAS_PRICE.LAST_ID
     *
     * @param lastId the value for GG_GAS_PRICE.LAST_ID
     *
     * @mbggenerated
     */
    public void setLastId(Long lastId) {
        this.lastId = lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_GAS_PRICE.DATE_CREATED
     *
     * @return the value of GG_GAS_PRICE.DATE_CREATED
     *
     * @mbggenerated
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_GAS_PRICE.DATE_CREATED
     *
     * @param dateCreated the value for GG_GAS_PRICE.DATE_CREATED
     *
     * @mbggenerated
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_GAS_PRICE.DATE_MODIFIED
     *
     * @return the value of GG_GAS_PRICE.DATE_MODIFIED
     *
     * @mbggenerated
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_GAS_PRICE.DATE_MODIFIED
     *
     * @param dateModified the value for GG_GAS_PRICE.DATE_MODIFIED
     *
     * @mbggenerated
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
}