package com.gasguz.model.mybatis;

import com.gasguz.action.AbstractForm;
import java.math.BigDecimal;
import java.util.Date;

public class Transaction extends AbstractForm {
  private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.VENDOR_LOCATION_ID
     *
     * @mbggenerated
     */
    private Long vendorLocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.GAS_GRADE_ID
     *
     * @mbggenerated
     */
    private Long gasGradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.COST
     *
     * @mbggenerated
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.TRANSACTION_TYPE
     *
     * @mbggenerated
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.DATE_CREATED
     *
     * @mbggenerated
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GG_TRANSACTION.DATE_MODIFIED
     *
     * @mbggenerated
     */
    private Date dateModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.USER_ID
     *
     * @return the value of GG_TRANSACTION.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.USER_ID
     *
     * @param userId the value for GG_TRANSACTION.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.VENDOR_LOCATION_ID
     *
     * @return the value of GG_TRANSACTION.VENDOR_LOCATION_ID
     *
     * @mbggenerated
     */
    public Long getVendorLocationId() {
        return vendorLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.VENDOR_LOCATION_ID
     *
     * @param vendorLocationId the value for GG_TRANSACTION.VENDOR_LOCATION_ID
     *
     * @mbggenerated
     */
    public void setVendorLocationId(Long vendorLocationId) {
        this.vendorLocationId = vendorLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.GAS_GRADE_ID
     *
     * @return the value of GG_TRANSACTION.GAS_GRADE_ID
     *
     * @mbggenerated
     */
    public Long getGasGradeId() {
        return gasGradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.GAS_GRADE_ID
     *
     * @param gasGradeId the value for GG_TRANSACTION.GAS_GRADE_ID
     *
     * @mbggenerated
     */
    public void setGasGradeId(Long gasGradeId) {
        this.gasGradeId = gasGradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.COST
     *
     * @return the value of GG_TRANSACTION.COST
     *
     * @mbggenerated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.COST
     *
     * @param cost the value for GG_TRANSACTION.COST
     *
     * @mbggenerated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.AMOUNT
     *
     * @return the value of GG_TRANSACTION.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.AMOUNT
     *
     * @param amount the value for GG_TRANSACTION.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.TRANSACTION_TYPE
     *
     * @return the value of GG_TRANSACTION.TRANSACTION_TYPE
     *
     * @mbggenerated
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.TRANSACTION_TYPE
     *
     * @param transactionType the value for GG_TRANSACTION.TRANSACTION_TYPE
     *
     * @mbggenerated
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.DATE_CREATED
     *
     * @return the value of GG_TRANSACTION.DATE_CREATED
     *
     * @mbggenerated
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.DATE_CREATED
     *
     * @param dateCreated the value for GG_TRANSACTION.DATE_CREATED
     *
     * @mbggenerated
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GG_TRANSACTION.DATE_MODIFIED
     *
     * @return the value of GG_TRANSACTION.DATE_MODIFIED
     *
     * @mbggenerated
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GG_TRANSACTION.DATE_MODIFIED
     *
     * @param dateModified the value for GG_TRANSACTION.DATE_MODIFIED
     *
     * @mbggenerated
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
}